BEGIN;

-- Static facts shared by every physical drone of the same model.
CREATE TABLE IF NOT EXISTS static.drone_models (
  model_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  model_code text UNIQUE NOT NULL,
  model_name text NOT NULL,
  manufacturer text,
  vehicle_class text NOT NULL,
  max_payload_kg numeric,
  nominal_range_km numeric,
  range_definition text,
  max_wind_mps numeric,
  wind_level_text text,
  positioning_accuracy text,
  noise_description text,
  takeoff_modes jsonb NOT NULL DEFAULT '[]'::jsonb,
  interface_type text,
  source_date date,
  source_note text,
  remarks text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS static.transport_capabilities (
  capability_code text PRIMARY KEY,
  capability_name text UNIQUE NOT NULL,
  description text
);

CREATE TABLE IF NOT EXISTS static.drone_model_capabilities (
  model_id bigint NOT NULL REFERENCES static.drone_models(model_id) ON DELETE CASCADE,
  capability_code text NOT NULL REFERENCES static.transport_capabilities(capability_code),
  support_status text NOT NULL CHECK (support_status IN ('supported', 'not_supported', 'requires_accessory', 'unknown')),
  support_method text,
  evidence_source text,
  verified_at date,
  PRIMARY KEY (model_id, capability_code)
);

INSERT INTO static.transport_capabilities (capability_code, capability_name, description) VALUES
  ('shockproof', '防震', '需要防震货箱或防震包装'),
  ('waterproof', '防水', '货箱或包装需要防水'),
  ('leakproof', '防漏', '液体或试剂需要密封防漏'),
  ('cold_chain', '冷链', '全程保持冷链条件'),
  ('temperature_controlled', '恒温', '保持规定温度范围'),
  ('low_noise', '静音要求', '对飞行噪音有额外限制')
ON CONFLICT (capability_code) DO UPDATE SET
  capability_name = EXCLUDED.capability_name,
  description = EXCLUDED.description;

INSERT INTO static.drone_models (
  model_code, model_name, manufacturer, vehicle_class, max_payload_kg,
  nominal_range_km, range_definition, max_wind_mps, wind_level_text,
  positioning_accuracy, noise_description, takeoff_modes, interface_type,
  source_date, source_note, remarks
) VALUES
  ('FP400V4', 'FP400 V4（第四代）', '美团', 'micro', 2.5, 10, '满载往返5km，单程最远10km', NULL, '最大抗风能力7级', '北斗三代地基增强，厘米级', '折叠三叶静音桨，噪音较上代下降50%', '["固定机场垂直起降"]', '闭环，不对外开放', '2025-04-01', '行业调研(1).docx', NULL),
  ('ARK40', '方舟40 ARK40', '顺丰丰翼', 'light', 10, 20, '公开航程20km', NULL, '未披露具体等级', 'RTK模块，降落精度可达厘米级', '未披露', '["固定起降场","索降","抛投","地面装卸"]', '闭环', '2024-04-01', '行业调研(1).docx', NULL),
  ('FZ90', '丰舟90', '顺丰丰翼', 'medium', NULL, 25, '公开医共体航线航程25km', NULL, '未披露', '未披露', '未披露', '["固定起降"]', '闭环', '2025-11-01', '行业调研(1).docx', '载重未披露'),
  ('TR9S', 'TR9S', '迅蚁', 'light', 9, 30, '公开航程30km', NULL, '较强抗风能力，等级未披露', '高精度传感器与5G通信', '未披露', '["货舱","索降"]', '闭环（自营）', '2024-07-01', '行业调研(1).docx', NULL),
  ('RA3P', 'RA3P', '迅蚁', 'light', NULL, 15, '公开资料为5–15km，按上限记录', NULL, '未披露', 'AI自动飞行算法与多组高精度传感器', '未披露', '["RH1自动枢纽站装卸"]', '闭环', '2025-11-01', '行业调研(1).docx', '载重未披露'),
  ('FC30', 'FlyCart 30', '大疆', 'heavy', 30, 16, '双电载重30kg时16km；单电载重40kg时8km', 12, '最大抗风12m/s', '启用RTK水平与垂直均±10cm', '未披露', '["货箱垂直起降","20m索降"]', 'Cloud API + ESDK + MSDK', '2023-08-01', '行业调研(1).docx', '系统按双电30kg/16km保守配置'),
  ('JDX20', 'JDX20 京鹊', '京东物流', 'light', 10, 24, '公开航程24km，任务半径5km', NULL, '6级大风环境下正常飞行', '高精度毫米波雷达，全向环境感知', '未披露', '["固定式货仓","自动装卸货箱","索降"]', '闭环', '2025-01-01', '行业调研(1).docx', NULL),
  ('JDX50', 'JDX50 京燕', '京东物流', 'medium', 15, NULL, '航程未披露', NULL, '未披露', '未披露', '未披露', '["固定起降场"]', '闭环', '2024-01-01', '行业调研(1).docx', '载重约15kg量级')
ON CONFLICT (model_code) DO UPDATE SET
  model_name=EXCLUDED.model_name, manufacturer=EXCLUDED.manufacturer,
  vehicle_class=EXCLUDED.vehicle_class, max_payload_kg=EXCLUDED.max_payload_kg,
  nominal_range_km=EXCLUDED.nominal_range_km, range_definition=EXCLUDED.range_definition,
  max_wind_mps=EXCLUDED.max_wind_mps, wind_level_text=EXCLUDED.wind_level_text,
  positioning_accuracy=EXCLUDED.positioning_accuracy, noise_description=EXCLUDED.noise_description,
  takeoff_modes=EXCLUDED.takeoff_modes, interface_type=EXCLUDED.interface_type,
  source_date=EXCLUDED.source_date, source_note=EXCLUDED.source_note,
  remarks=EXCLUDED.remarks, updated_at=now();

-- Fill concrete model candidates for rule rows that previously only carried a class.
UPDATE static.vehicle_rules SET remarks = CASE vehicle_class
  WHEN 'micro' THEN '候选机型: FP400 V4'
  WHEN 'light' THEN '候选机型: 方舟40 / TR9S / JDX20'
  WHEN 'medium' THEN '候选机型: FC30 / JDX50'
  WHEN 'heavy' THEN '候选机型: FC30 / JDX50'
  ELSE remarks
END
WHERE remarks IS NULL OR btrim(remarks) = '';

-- The survey does not establish built-in cargo protection for most models.
-- Record accessories/unknown explicitly instead of inventing support.
INSERT INTO static.drone_model_capabilities (model_id, capability_code, support_status, support_method, evidence_source)
SELECT m.model_id, c.capability_code,
  CASE
    WHEN c.capability_code = 'low_noise' AND m.model_code = 'FP400V4' THEN 'supported'
    WHEN c.capability_code IN ('shockproof','waterproof','leakproof','cold_chain','temperature_controlled') THEN 'requires_accessory'
    ELSE 'unknown'
  END,
  CASE
    WHEN c.capability_code = 'low_noise' AND m.model_code = 'FP400V4' THEN '静音桨，调研资料称噪音较上代下降50%'
    WHEN c.capability_code IN ('shockproof','waterproof','leakproof','cold_chain','temperature_controlled') THEN '需由运营端确认对应货箱或包装配置'
    ELSE '调研资料未披露'
  END,
  '行业调研(1).docx'
FROM static.drone_models m CROSS JOIN static.transport_capabilities c
ON CONFLICT (model_id, capability_code) DO UPDATE SET
  support_status=EXCLUDED.support_status,
  support_method=EXCLUDED.support_method,
  evidence_source=EXCLUDED.evidence_source;

ALTER TABLE runtime.drones
  ADD COLUMN IF NOT EXISTS model_id bigint REFERENCES static.drone_models(model_id),
  ADD COLUMN IF NOT EXISTS fault_code text,
  ADD COLUMN IF NOT EXISTS fault_message text,
  ADD COLUMN IF NOT EXISTS state_source text NOT NULL DEFAULT 'simulation',
  ADD COLUMN IF NOT EXISTS last_seen_at timestamptz,
  ADD COLUMN IF NOT EXISTS telemetry_updated_at timestamptz;

UPDATE runtime.drones d SET model_id=m.model_id
FROM static.drone_models m WHERE d.drone_code=m.model_code AND d.model_id IS DISTINCT FROM m.model_id;

ALTER TABLE runtime.tasks
  ADD COLUMN IF NOT EXISTS requester_confirmed_at timestamptz,
  ADD COLUMN IF NOT EXISTS requester_confirmed_by text,
  ADD COLUMN IF NOT EXISTS recommended_drone_id bigint REFERENCES runtime.drones(drone_id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS resource_confirmed_at timestamptz,
  ADD COLUMN IF NOT EXISTS resource_confirmed_by text,
  ADD COLUMN IF NOT EXISTS selection_reason text;

CREATE TABLE IF NOT EXISTS runtime.task_drone_candidates (
  candidate_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  task_id bigint NOT NULL REFERENCES runtime.tasks(task_id) ON DELETE CASCADE,
  route_id bigint REFERENCES runtime.routes(route_id) ON DELETE CASCADE,
  drone_id bigint NOT NULL REFERENCES runtime.drones(drone_id) ON DELETE CASCADE,
  recommendation_rank integer,
  is_eligible boolean NOT NULL,
  is_recommended boolean NOT NULL DEFAULT false,
  task_distance_km numeric,
  available_range_km numeric,
  battery_percent numeric,
  safety_factor numeric NOT NULL DEFAULT 0.7,
  payload_passed boolean NOT NULL,
  range_passed boolean NOT NULL,
  battery_passed boolean NOT NULL,
  status_passed boolean NOT NULL,
  capability_passed boolean NOT NULL,
  matched_capabilities jsonb NOT NULL DEFAULT '[]'::jsonb,
  missing_capabilities jsonb NOT NULL DEFAULT '[]'::jsonb,
  rejection_reasons jsonb NOT NULL DEFAULT '[]'::jsonb,
  recommendation_reason text,
  evaluated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (task_id, route_id, drone_id)
);

CREATE INDEX IF NOT EXISTS idx_task_drone_candidates_task_rank
  ON runtime.task_drone_candidates(task_id, recommendation_rank, candidate_id);

-- Include the earlier explanation migration because existing packaged databases
-- may have been created before migration 007 was applied.
ALTER TABLE runtime.routes
  ADD COLUMN IF NOT EXISTS agent_explanation jsonb,
  ADD COLUMN IF NOT EXISTS explanation_status text NOT NULL DEFAULT 'pending',
  ADD COLUMN IF NOT EXISTS explanation_generated_at timestamptz,
  ADD COLUMN IF NOT EXISTS explanation_error text;

COMMIT;
