BEGIN;

ALTER TABLE runtime.tasks
  ADD COLUMN IF NOT EXISTS assigned_drone_id bigint,
  ADD COLUMN IF NOT EXISTS assigned_node_id bigint,
  ADD COLUMN IF NOT EXISTS completed_at timestamp without time zone;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'tasks_assigned_drone_id_fkey'
      AND conrelid = 'runtime.tasks'::regclass
  ) THEN
    ALTER TABLE runtime.tasks
      ADD CONSTRAINT tasks_assigned_drone_id_fkey
      FOREIGN KEY (assigned_drone_id)
      REFERENCES runtime.drones(drone_id)
      ON DELETE SET NULL;
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'tasks_assigned_node_id_fkey'
      AND conrelid = 'runtime.tasks'::regclass
  ) THEN
    ALTER TABLE runtime.tasks
      ADD CONSTRAINT tasks_assigned_node_id_fkey
      FOREIGN KEY (assigned_node_id)
      REFERENCES static.fixed_nodes(node_id)
      ON DELETE SET NULL;
  END IF;
END
$$;

ALTER TABLE runtime.tasks DROP CONSTRAINT IF EXISTS tasks_status_check;
ALTER TABLE runtime.tasks
  ADD CONSTRAINT tasks_status_check CHECK (
    status = ANY (ARRAY[
      'submitted', 'parsed', 'reviewing', 'approved', 'rejected',
      'planning', 'planned', 'replanned', 'dispatched', 'running',
      'arriving', 'completed', 'aborted', 'suspended'
    ])
  );

CREATE TABLE IF NOT EXISTS runtime.node_states (
  node_id bigint PRIMARY KEY REFERENCES static.fixed_nodes(node_id) ON DELETE CASCADE,
  availability text NOT NULL DEFAULT 'available' CHECK (
    availability = ANY (ARRAY['available', 'reserved', 'occupied', 'maintenance', 'offline'])
  ),
  door_state text NOT NULL DEFAULT 'closed' CHECK (
    door_state = ANY (ARRAY['closed', 'opening', 'open', 'closing', 'fault'])
  ),
  delivery_state text NOT NULL DEFAULT 'idle',
  fault_code text,
  task_id bigint REFERENCES runtime.tasks(task_id) ON DELETE SET NULL,
  updated_at timestamp without time zone NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_node_states_task
  ON runtime.node_states (task_id)
  WHERE task_id IS NOT NULL;

INSERT INTO runtime.node_states (node_id, availability)
SELECT
  node_id,
  CASE status
    WHEN 'active' THEN 'available'
    WHEN 'maintenance' THEN 'maintenance'
    ELSE 'offline'
  END
FROM static.fixed_nodes
ON CONFLICT (node_id) DO NOTHING;

CREATE TABLE IF NOT EXISTS runtime.operation_events (
  event_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  task_id bigint NOT NULL REFERENCES runtime.tasks(task_id) ON DELETE CASCADE,
  event_type text NOT NULL,
  actor text,
  details jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamp without time zone NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_operation_events_task_created
  ON runtime.operation_events (task_id, created_at DESC);

CREATE UNIQUE INDEX IF NOT EXISTS idx_runtime_drones_active_task
  ON runtime.drones (task_id)
  WHERE task_id IS NOT NULL;

COMMIT;
