BEGIN;

CREATE TABLE IF NOT EXISTS runtime.audit_events (
  audit_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_type text NOT NULL,
  category text NOT NULL CHECK (category = ANY (ARRAY['task', 'approval', 'operation', 'safety'])),
  task_id bigint REFERENCES runtime.tasks(task_id) ON DELETE CASCADE,
  title text NOT NULL,
  description text NOT NULL DEFAULT '',
  actor_role text NOT NULL DEFAULT 'system',
  actor_name text NOT NULL DEFAULT '系统',
  actor_department text NOT NULL DEFAULT '',
  resource_type text NOT NULL DEFAULT '',
  resource_id text NOT NULL DEFAULT '',
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamp without time zone NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_audit_events_created
  ON runtime.audit_events (created_at DESC, audit_id DESC);

CREATE INDEX IF NOT EXISTS idx_audit_events_task_created
  ON runtime.audit_events (task_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_audit_events_category_created
  ON runtime.audit_events (category, created_at DESC);

COMMIT;
