const TASK_STATUS = Object.freeze({
  SUBMITTED: 'SUBMITTED',
  AGENT_REVIEWED: 'AGENT_REVIEWED',
  PENDING_APPROVAL: 'PENDING_APPROVAL',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
  PROVIDER_ACCEPTED: 'PROVIDER_ACCEPTED',
  READY_FOR_TAKEOFF: 'READY_FOR_TAKEOFF',
  IN_FLIGHT: 'IN_FLIGHT',
  ARRIVED: 'ARRIVED',
  PICKED_UP: 'PICKED_UP',
  COMPLETED: 'COMPLETED',
  EXCEPTION: 'EXCEPTION',
  CANCELLED: 'CANCELLED',
})

const STATUS_LABELS = Object.freeze({
  [TASK_STATUS.SUBMITTED]: '申请已提交',
  [TASK_STATUS.AGENT_REVIEWED]: 'AI 分析完成',
  [TASK_STATUS.PENDING_APPROVAL]: '校方审核中',
  [TASK_STATUS.APPROVED]: '校方已批准',
  [TASK_STATUS.REJECTED]: '申请未通过',
  [TASK_STATUS.PROVIDER_ACCEPTED]: '企业已接单',
  [TASK_STATUS.READY_FOR_TAKEOFF]: '等待起飞',
  [TASK_STATUS.IN_FLIGHT]: '配送飞行中',
  [TASK_STATUS.ARRIVED]: '已到达接驳点',
  [TASK_STATUS.PICKED_UP]: '已取件',
  [TASK_STATUS.COMPLETED]: '配送已完成',
  [TASK_STATUS.EXCEPTION]: '配送异常',
  [TASK_STATUS.CANCELLED]: '任务已取消',
})

const ALLOWED_TRANSITIONS = Object.freeze({
  [TASK_STATUS.SUBMITTED]: [TASK_STATUS.AGENT_REVIEWED],
  [TASK_STATUS.AGENT_REVIEWED]: [TASK_STATUS.PENDING_APPROVAL, TASK_STATUS.CANCELLED],
  [TASK_STATUS.PENDING_APPROVAL]: [TASK_STATUS.APPROVED, TASK_STATUS.REJECTED, TASK_STATUS.CANCELLED],
  [TASK_STATUS.APPROVED]: [TASK_STATUS.PROVIDER_ACCEPTED, TASK_STATUS.CANCELLED],
  [TASK_STATUS.REJECTED]: [],
  [TASK_STATUS.PROVIDER_ACCEPTED]: [TASK_STATUS.READY_FOR_TAKEOFF, TASK_STATUS.EXCEPTION, TASK_STATUS.CANCELLED],
  [TASK_STATUS.READY_FOR_TAKEOFF]: [TASK_STATUS.IN_FLIGHT, TASK_STATUS.EXCEPTION, TASK_STATUS.CANCELLED],
  [TASK_STATUS.IN_FLIGHT]: [TASK_STATUS.ARRIVED, TASK_STATUS.EXCEPTION],
  [TASK_STATUS.ARRIVED]: [TASK_STATUS.PICKED_UP, TASK_STATUS.EXCEPTION],
  [TASK_STATUS.PICKED_UP]: [TASK_STATUS.COMPLETED],
  [TASK_STATUS.COMPLETED]: [],
  [TASK_STATUS.EXCEPTION]: [TASK_STATUS.READY_FOR_TAKEOFF, TASK_STATUS.IN_FLIGHT, TASK_STATUS.CANCELLED],
  [TASK_STATUS.CANCELLED]: [],
})

function getStatusLabel(status) {
  return STATUS_LABELS[status] || status
}

function canTransition(fromStatus, toStatus) {
  return Boolean(ALLOWED_TRANSITIONS[fromStatus]?.includes(toStatus))
}

function assertTransition(fromStatus, toStatus) {
  if (!TASK_STATUS[fromStatus] || !TASK_STATUS[toStatus]) {
    throw new Error(`未知任务状态：${fromStatus} -> ${toStatus}`)
  }
  if (!canTransition(fromStatus, toStatus)) {
    throw new Error(`不允许任务从“${getStatusLabel(fromStatus)}”变更为“${getStatusLabel(toStatus)}”`)
  }
}

module.exports = {
  TASK_STATUS,
  STATUS_LABELS,
  getStatusLabel,
  canTransition,
  assertTransition,
}
